import { useShapeStore } from "@/store/useShapeStore";
import { Shape } from "@/types/shape";
import rough from "roughjs/bin/rough";
import { generateDrawable } from "@/utils/draw";
import isEqual from "lodash.isequal";
import { useCursorStore } from "@/store/useCursorStore";
import { usePreviewStore } from "@/store/usePreviewStore";

const wsRef: { current: WebSocket | null } = { current: null };

const connect = (
  roomId: string,
  token: string,
  callbacks?: {
    onOpen?: () => void;
    onError?: (err: Event) => void;
    onClose?: () => void;
    onParticipantsUpdate?: (participants: Array<{ userId: string; name: string }>) => void;
  }
): Promise<void> => {
  return new Promise((resolve, reject) => {
    const serverUrl = process.env.NEXT_PUBLIC_WS_SERVER_URL;
    const ws = new WebSocket(`${serverUrl}?token=${token}`);
    wsRef.current = ws;

    ws.onopen = () => {
      ws.send(JSON.stringify({ type: "join-room", roomId }));
      callbacks?.onOpen?.();
      resolve();
    };

    ws.onerror = (err) => {
      console.error("WebSocket error", err);
      callbacks?.onError?.(err);
      reject(err);
    };

    ws.onmessage = (event) => {
      const data = JSON.parse(event.data);
      if (data.type === "participants-update") {
        const participants = data.participants || [];
        const ids = participants.map((p: { userId: string }) => p.userId);
        useCursorStore.getState().keepOnly(ids);
        usePreviewStore.getState().keepOnly(ids);
        callbacks?.onParticipantsUpdate?.(participants);
        return;
      }

      if (data.type === "preview") {
        const shape: Shape | null = data.shape;
        if (shape) {
          const drawable = generateDrawable(
            rough.generator(),
            shape,
            useShapeStore.getState().zoom ?? 1
          );
          shape.drawable = drawable ?? undefined;
        }
        usePreviewStore.getState().setPreview(data.userId, shape);
        return;
      }

      if (data.type === "cursor") {
        useCursorStore.getState().setCursor({
          userId: data.userId,
          name: data.name,
          x: data.x,
          y: data.y,
        });
        return;
      }

      // console.log("shape received");
      if (data.type === "chat") {
        const { roomId, message: shape } = data;
        const { getShapes, updateShape, addShape } = useShapeStore.getState();
        const existing = getShapes(roomId).find((s) => s.id === shape.id);
        if (shape.type === "deleted") {
          const newShapes = getShapes(roomId).filter((s) => s.id !== shape.id);
          useShapeStore.getState().setShapes(roomId, newShapes);
          return;
        }

        const generator = rough.generator();
        shape.drawable = generateDrawable(
          generator,
          shape,
          useShapeStore.getState().zoom ?? 1
        );
        if (existing) {
          if(!isEqual(existing, shape)) {
          updateShape(roomId, shape);
          // console.log("updated shape");
          }
        } else {
          addShape(roomId, shape);
          // console.log("updated shape");
        }
      }
    };

    ws.onclose = () => {
      console.warn("WebSocket closed");
      useCursorStore.getState().clearCursors();
      usePreviewStore.getState().clearPreviews();
      callbacks?.onClose?.();
      wsRef.current = null;
    };
  });
};

const sendShape = (roomId: string, shape: Shape) => {
  const ws = wsRef.current;

  if (ws && ws.readyState === WebSocket.OPEN) {
    ws.send(
      JSON.stringify({
        type: "chat",
        roomId,
        message: shape,
      })
    );
    // console.log("send");
  } else {
    // console.warn("WebSocket not ready, shape not sent");
  }
};

const sendCursor = (roomId: string, x: number, y: number) => {
  const ws = wsRef.current;
  if (ws && ws.readyState === WebSocket.OPEN) {
    ws.send(JSON.stringify({ type: "cursor", roomId, x, y }));
  }
};

let lastPreviewSent = 0;

// Pass null to clear our in-progress preview on other clients.
// `force` skips throttling (used for text, where a dropped keystroke would linger).
const sendPreview = (roomId: string, shape: Shape | null, force = false) => {
  const ws = wsRef.current;
  if (roomId === "standalone" || !ws || ws.readyState !== WebSocket.OPEN) return;

  if (shape && !force) {
    const now = performance.now();
    if (now - lastPreviewSent < 33) return;
    lastPreviewSent = now;
  }

  // The drawable is regenerated by the receiver; don't ship it over the wire.
  const message = shape ? { ...shape, drawable: undefined } : null;
  ws.send(JSON.stringify({ type: "preview", roomId, shape: message }));
};

const disconnect = () => {
  wsRef.current?.close();
  wsRef.current = null;
  useCursorStore.getState().clearCursors();
  usePreviewStore.getState().clearPreviews();
};

export const wsClient = {
  connect,
  sendShape,
  sendCursor,
  sendPreview,
  disconnect,
};
